num_workers: 0
worker_heap_limit_mb: 250

logging:
  level: trace

services:
    - name: mathoid
      conf:
          svg: true
          img: true
          texvcinfo: true
          speech: true
          speech_on: false
          mj_config:
              extensions: "TeX/color,TeX/mediawiki-texvc,TeX/mhchem"
              MathJax:
                  menuSettings:
                      semantics: true
                  SVG:
                      font: "TeX"
                  TeX:
                      noErrors:
                          disabled: true
          no_check: true
          dpi: 180
          svgo: false
